### ISSUE TITLE
snapshot uninstallable

### ISSUE THREAD

**Issue by themr0c** [dboissier/nosql4idea#3]
I get this error when trying to install the snapshot on pycharm community edition 5.0.2, on Linux, with openjdk 7. What is going wrong ?

```
Plugin 'NoSql Plugin' is incompatible with this installation
```

**Comment by dboissier** [comment]
Hi,

please test this [SNAPSHOT](https://github.com/dboissier/nosql4idea/raw/master/snapshot/nosql4idea-0.1.0-SNAPSHOT-Idea15-distribution.zip) and tell me if it works

Sorry for the late response
