### ISSUE TITLE
Cannot add server item

### ISSUE THREAD

**Issue by Delagen** [dboissier/nosql4idea#4]
All fields filled, test connection successful but click on ok button do nothing

**Comment by dboissier** [comment]
Hi,

Could you please be more precise (database vendor, local or remote server) and add snapshot if possible?

Thanks

**Comment by Delagen** [comment]
WebStorm 11.0.3 on windows.
Redis 2.8.1 (win) + Redis 3.0.6 (centos) + MongoDb 3.2 (centos)

Open Settings -> Add Server -> Enter settings -> Test Connection (success) -> Press OK (dialog does not closed and new item does not added to list)

![image](https://cloud.githubusercontent.com/assets/783335/12046497/5378b68a-aecb-11e5-8f83-ebcf02148481.png)

![test](https://cloud.githubusercontent.com/assets/783335/12046513/9e494e90-aecb-11e5-8cfa-a8fc3eb9ce73.png)

**Comment by dboissier** [comment]
Hi,

I found the bug root cause and fixed it. A new snapshots are available (same links).

Tell me if it works

**Comment by delagen** [comment]
works now ))
